### ISSUE TITLE
insert 语句主键id获取不到

### ISSUE THREAD

**Issue by SheltonZhu** [godoes/gorm-oracle#11]
```sql
INSERT INTO doc_compare_user (name,account,password,status,ctm,utm,type,admin_id,note,expire_time,deleted,source_id,sso_user_unique_id) VALUES ('test','test','d9d7392be643cc709bbcb403e441b163',1,'2024-01-17 18:08:00.598','2024-01-17 18:08:00.598',0,20230831,'','2121-01-01 00:00:00',-1,-1,'3f752d69-bf9b-4f2f-8f4f-d34d9a201bfc') /*--*/RETURNING id INTO '{{} 0xc001688a90 false}' /*-sql.Out{}-*/
```
我的主键是int32 , insertTo.Kind()  = 22, 是指针类型
```go
func getDefaultValues(db *gorm.DB, idx int) {
	insertTo := db.Statement.ReflectValue
	switch insertTo.Kind() {
	case reflect.Slice, reflect.Array:
		insertTo = insertTo.Index(idx)
	default:
	}

	for _, val := range db.Statement.Vars {
		switch v := val.(type) {
		case sql.Out:
			switch insertTo.Kind() {
			case reflect.Slice, reflect.Array:
				for i := insertTo.Len() - 1; i >= 0; i-- {
					rv := insertTo.Index(i)
					if reflect.Indirect(rv).Kind() != reflect.Struct {
						break
					}

					_, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.Context, rv)
					if isZero {
						_ = db.AddError(db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.Context, rv, v.Dest))
					}
				}
			case reflect.Struct:
				_, isZero := db.Statement.Schema.PrioritizedPrimaryField.ValueOf(db.Statement.Context, insertTo)
				if isZero {
					_ = db.AddError(db.Statement.Schema.PrioritizedPrimaryField.Set(db.Statement.Context, insertTo, v.Dest))
				}
			default:
                               
                                 // 会跳到这里 insertTo.Kind()  = 22, 是指针类型
				}
			}
		default:
		}
	}
}
```
![企业微信截图_17054870027306](https://github.com/godoes/gorm-oracle/assets/26734784/4f1122dd-0ecd-427d-a962-b54e328c592c)

**Comment by iTanken** [comment]
请问你用的哪个版本？我用最新版 [`v1.5.18`](https://github.com/godoes/gorm-oracle/tree/v1.5.18) 测试 `int32` 类型的主键是返回了值的：

![image](https://github.com/godoes/gorm-oracle/assets/23544702/384bea44-f0c4-4b69-8bba-04a9f68b3db8)

**Comment by SheltonZhu** [comment]
> 请问你用的哪个版本？我用最新版 [`v1.5.18`](https://github.com/godoes/gorm-oracle/tree/v1.5.18) 测试 `int32` 类型的主键是返回了值的：
> 
> ![image](https://private-user-images.githubusercontent.com/23544702/297354509-384bea44-f0c4-4b69-8bba-04a9f68b3db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTI2MzUsIm5iZiI6MTcwNTQ5MjMzNSwicGF0aCI6Ii8yMzU0NDcwMi8yOTczNTQ1MDktMzg0YmVhNDQtZjBjNC00YjY5LThiYmEtMDRhOWY2OGIzZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDExNTIxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZWYxYTMxYzI5MDM0YzY4NTllNTM0MjUzY2FjOTY2Njc2OWI2ZDgzM2VmYzM3MWFmYTk3OWVkOGU5YjM2YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.stWxbjR8MCYkQhoM1lz5R7rHdT3JU_8WenPr8LnKoqU)

	github.com/godoes/gorm-oracle v1.5.18

**Comment by SheltonZhu** [comment]
> 请问你用的哪个版本？我用最新版 [`v1.5.18`](https://github.com/godoes/gorm-oracle/tree/v1.5.18) 测试 `int32` 类型的主键是返回了值的：
> 
> ![image](https://private-user-images.githubusercontent.com/23544702/297354509-384bea44-f0c4-4b69-8bba-04a9f68b3db8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0OTUwMTQsIm5iZiI6MTcwNTQ5NDcxNCwicGF0aCI6Ii8yMzU0NDcwMi8yOTczNTQ1MDktMzg0YmVhNDQtZjBjNC00YjY5LThiYmEtMDRhOWY2OGIzZGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDEyMzE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMzI2MTUzYzY0MWYwODYyNGRiNDU3MmJjZWE0ZDE3NzRmYTEzMzFlYTViOTc5MmFkNDY5OGNlYmE0ZWQ1YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRXv89NrW3XN1PFQN1fz3Xw2FKDVM-V40N8M8qPg9XM)

还有一个问题想请教一下，定义struct的时候，gorm 的tag是小写下划线，oracle创建数据库的时候是大写下划线，go-ora驱动的 rows.Columns方法返回的是全大写，我看gorm 绑定字段的时候是去找tag也就是dbname和keyname，导致绑定不上数据，但是你给的这个似乎没问题？

**Comment by iTanken** [comment]
> > 请问你用的哪个版本？我用最新版 [`v1.5.18`](https://github.com/godoes/gorm-oracle/tree/v1.5.18) 测试 `int32` 类型的主键是返回了值的：
> > ![image](https://private-user-images.githubusercontent.com/23544702/297354509-384bea44-f0c4-4b69-8bba-04a9f68b3db8.png)
> 
> 还有一个问题想请教一下，定义struct的时候，gorm 的tag是小写下划线，oracle创建数据库的时候是大写下划线，go-ora驱动的 rows.Columns方法返回的是全大写，我看gorm 绑定字段的时候是去找tag也就是dbname和keyname，导致绑定不上数据，但是你给的这个似乎没问题？

可以参考这个问题的回答：

https://github.com/godoes/gorm-oracle/issues/8#issuecomment-1877990549

**Comment by SheltonZhu** [comment]
> > > 请问你用的哪个版本？我用最新版 [`v1.5.18`](https://github.com/godoes/gorm-oracle/tree/v1.5.18) 测试 `int32` 类型的主键是返回了值的：
> > > ![image](https://private-user-images.githubusercontent.com/23544702/297354509-384bea44-f0c4-4b69-8bba-04a9f68b3db8.png)
> > 
> > 
> > 还有一个问题想请教一下，定义struct的时候，gorm 的tag是小写下划线，oracle创建数据库的时候是大写下划线，go-ora驱动的 rows.Columns方法返回的是全大写，我看gorm 绑定字段的时候是去找tag也就是dbname和keyname，导致绑定不上数据，但是你给的这个似乎没问题？
> 
> 可以参考这个问题的回答：
> 
> [#8 (comment)](https://github.com/godoes/gorm-oracle/issues/8#issuecomment-1877990549)
我使用的配置如下, sql是可以执行的, 结果也能拿得到, 是在rows 绑定到 struct的过程中,没有绑定上, 通过调试发现 在 `gorm/scan.go`的 `func Scan(rows Rows, db *DB, mode ScanMode) `中会去获取go-ora的列名 `columns, _          = rows.Columns()` 拿到的都是全大写, 然后去  `sch.LookUpField(column)`,寻找,但是只在`FieldsByDBName`和`FieldsByName`中找, `FieldsByDBName`中是gorm 的columu, tag,全小写, 所以找不到,最后没有把数据绑定上.
```go
	options := map[string]string{
		"CONNECTION TIMEOUT": "90",
		"LANGUAGE":           "SIMPLIFIED CHINESE",
		"TERRITORY":          "CHINA",
		"SSL":                "false",
		"lob fetch":          "post",
	}
	// oracle://user:password@127.0.0.1:1521/database
	url := oracle.BuildUrl(opts.Host, opts.Port, opts.Database, opts.Username, opts.Password, options)
	return oracle.New(oracle.Config{
		DSN:                 url,
		IgnoreCase:          false, // query conditions are not case-sensitive
		NamingCaseSensitive: false, // whether naming is case-sensitive
	}), nil
```
```
var (
		columns, _          = rows.Columns()
		values              = make([]interface{}, len(columns))
		initialized         = mode&ScanInitialized != 0
		update              = mode&ScanUpdate != 0
		onConflictDonothing = mode&ScanOnConflictDoNothing != 0
	)
```
```
func (schema Schema) LookUpField(name string) *Field {
	if field, ok := schema.FieldsByDBName[name]; ok {
		return field
	}
	if field, ok := schema.FieldsByName[name]; ok {
		return field
	}
	return nil
}
```

**Comment by iTanken** [comment]
> 我使用的配置如下, sql是可以执行的, 结果也能拿得到, 是在rows 绑定到 struct的过程中,没有绑定上, 通过调试发现 在 `gorm/scan.go`的 `func Scan(rows Rows, db *DB, mode ScanMode) `中会去获取go-ora的列名 `columns, _ = rows.Columns()` 拿到的都是全大写, 然后去 `sch.LookUpField(column)`,寻找,但是只在`FieldsByDBName`和`FieldsByName`中找, `FieldsByDBName`中是gorm 的columu, tag,全小写, 所以找不到,最后没有把数据绑定上.

启用 `NamingCaseSensitive` 后会使用双引号包裹字段名，自动迁移表结构时创建的字段才会是小写的，否则字段名没有加双引号 Oracle 数据库默认创建大写字段，就不能跟 tag 指定的小写字段匹配上。所以要么 tag 改成大写，要么启用 `NamingCaseSensitive`。

**Comment by SheltonZhu** [comment]
> 否则字段名没

好的,感谢大佬解答

我这边因为某些原因不能使用自动迁移表结构功能, 创建的都是大写字段,目前是写了了插件在`FieldsByDBName`中添加了大写的key来解决的

**Comment by iTanken** [comment]
> 感谢大佬解答

额，互相交流，没必要搞这些名词。这个库本身还不够完善，有人反馈问题我也很感谢。

> 我这边因为某些原因不能使用自动迁移表结构功能, 创建的都是大写字段

如果是使用 SQL 脚本创建表结构，想要小写表名和字段名可以手动加双引号，比如：

<details><summary>创建小写表名和字段名</summary>

```sql
-- drop table SYSTEM."test_user";
create table SYSTEM."test_user" (
    "id"                   NUMBER generated as identity primary key,
    "name"                 VARCHAR2(50),
    "account"              VARCHAR2(50),
    "password"             VARCHAR2(512),
    "email"                VARCHAR2(128),
    "phone_number"         VARCHAR2(15),
    "sex"                  CHAR,
    "birthday"             TIMESTAMP(6) WITH TIME ZONE,
    "user_type"            NUMBER,
    "enabled"              NUMBER(1),
    "remark"               VARCHAR2(1024),
    "uid"                  VARCHAR2(50),
    "add_new_column"       VARCHAR2(100),
    "comment_single_quote" VARCHAR2(1024)
);

comment on table SYSTEM."test_user" is '用户信息表';
comment on column SYSTEM."test_user"."id" is '自增 ID';
comment on column SYSTEM."test_user"."name" is '用户姓名';
comment on column SYSTEM."test_user"."account" is '登录账号';
comment on column SYSTEM."test_user"."password" is '登录密码（密文）';
comment on column SYSTEM."test_user"."email" is '邮箱地址';
comment on column SYSTEM."test_user"."phone_number" is 'E.164';
comment on column SYSTEM."test_user"."sex" is '性别';
comment on column SYSTEM."test_user"."birthday" is '生日';
comment on column SYSTEM."test_user"."user_type" is '用户类型';
comment on column SYSTEM."test_user"."enabled" is '是否可用';
comment on column SYSTEM."test_user"."remark" is '备注信息';
comment on column SYSTEM."test_user"."uid" is '用户身份标识';
comment on column SYSTEM."test_user"."add_new_column" is '测试添加新字段';
comment on column SYSTEM."test_user"."comment_single_quote" is '注释中存在单引号''['']''';
```

</details>

**Comment by SheltonZhu** [comment]
是的，现在在想办法批量加引号😂

**Comment by iTanken** [comment]
我用 Oracle19c 和你给的结构体测试也返回了 ID，确定你数据库里的 ID 字段是自增的吗？

<details><summary>使用 Oracle19c 和 DocCompareUser 结构体测试结果</summary>

![image](https://github.com/godoes/gorm-oracle/assets/23544702/ad3e1356-ddbb-4966-b0ab-841b6c7ddfcf)

</details>

**Comment by SheltonZhu** [comment]
> 我用 Oracle19c 和你给的结构体测试也返回了 ID，确定你数据库里的 ID 字段是自增的吗？`DocCompareUser` 结构体有没有 `AfterFind` 类的钩子方法或其他处理？
> 
> 使用 Oracle19c 和 DocCompareUser 结构体测试结果

```sql
CREATE TABLE "doc_compare_user" (
    "id" NUMBER(10, 0) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 143 INCREMENT BY 1 MINVALUE 1 NOMAXVALUE,
    "name" VARCHAR2(255 CHAR),
    "account" VARCHAR2(255 CHAR),
    "password" VARCHAR2(255 CHAR),
    "status" NUMBER(10, 0),
    "ctm" TIMESTAMP(0),
    "utm" TIMESTAMP(0),
    "type" NUMBER(10, 0),
    "admin_id" NUMBER(10, 0) NOT NULL,
    "note" VARCHAR2(10 CHAR),
    "expire_time" TIMESTAMP(0) NOT NULL,
    "deleted" NUMBER(10, 0) NOT NULL,
    "source_id" NUMBER(3, 0) NOT NULL,
    "sso_user_unique_id" VARCHAR2(255 CHAR) NOT NULL
);

COMMENT ON COLUMN "doc_compare_user"."id" IS '自增id';
```
是这么写的

**Comment by SheltonZhu** [comment]
```
type docCompareUserDo struct{ gen.DO }

type IDocCompareUserDo interface {
	gen.SubQuery
	Debug() IDocCompareUserDo
	WithContext(ctx context.Context) IDocCompareUserDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDocCompareUserDo
	WriteDB() IDocCompareUserDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDocCompareUserDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDocCompareUserDo
	Not(conds ...gen.Condition) IDocCompareUserDo
	Or(conds ...gen.Condition) IDocCompareUserDo
	Select(conds ...field.Expr) IDocCompareUserDo
	Where(conds ...gen.Condition) IDocCompareUserDo
	Order(conds ...field.Expr) IDocCompareUserDo
	Distinct(cols ...field.Expr) IDocCompareUserDo
	Omit(cols ...field.Expr) IDocCompareUserDo
	Join(table schema.Tabler, on ...field.Expr) IDocCompareUserDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDocCompareUserDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDocCompareUserDo
	Group(cols ...field.Expr) IDocCompareUserDo
	Having(conds ...gen.Condition) IDocCompareUserDo
	Limit(limit int) IDocCompareUserDo
	Offset(offset int) IDocCompareUserDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDocCompareUserDo
	Unscoped() IDocCompareUserDo
	Create(values ...*model.DocCompareUser) error
	CreateInBatches(values []*model.DocCompareUser, batchSize int) error
	Save(values ...*model.DocCompareUser) error
	First() (*model.DocCompareUser, error)
	Take() (*model.DocCompareUser, error)
	Last() (*model.DocCompareUser, error)
	Find() ([]*model.DocCompareUser, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DocCompareUser, err error)
	FindInBatches(result *[]*model.DocCompareUser, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DocCompareUser) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDocCompareUserDo
	Assign(attrs ...field.AssignExpr) IDocCompareUserDo
	Joins(fields ...field.RelationField) IDocCompareUserDo
	Preload(fields ...field.RelationField) IDocCompareUserDo
	FirstOrInit() (*model.DocCompareUser, error)
	FirstOrCreate() (*model.DocCompareUser, error)
	FindByPage(offset int, limit int) (result []*model.DocCompareUser, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDocCompareUserDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}
```

**Comment by iTanken** [comment]
@SheltonZhu https://github.com/godoes/gorm-oracle/releases/tag/v1.5.19 已修复并发布，有空可以试一下。

**Comment by iTanken** [comment]
> 还有就是 left join order by 的时候，生成的order by 字段名没有带表名导致执行失败，但是我不确定是不是驱动造成的，mysql是正常的

这个问题可以再详细描述一下吗？比如添加一些示例代码以及 MySQL 和 Oracle 的对比 SQL。

**Comment by SheltonZhu** [comment]
> > 还有就是 left join order by 的时候，生成的order by 字段名没有带表名导致执行失败，但是我不确定是不是驱动造成的，mysql是正常的
> 
> 这个问题可以再详细描述一下吗？比如添加一些示例代码以及 MySQL 和 Oracle 的对比 SQL。

是我看错了， 是count语句生成的不一样： mysql 生成 `select count(*) from xxx` 但是 oracle 生成的 `select count(*) from xxx by id` , 我再看看， 有问题我再另提issue。

**Comment by SheltonZhu** [comment]
```
func (d Dialector) RewriteLimit(c clause.Clause, builder clause.Builder) {
	if limit, ok := c.Expression.(clause.Limit); ok {
		// if stmt, ok := builder.(*gorm.Statement); ok {
		// 	if _, ok := stmt.Clauses["ORDER BY"]; !ok {
		// 		s := stmt.Schema
		// 		_, _ = builder.WriteString("ORDER BY ")
		// 		if s != nil && s.PrioritizedPrimaryField != nil {
		// 			builder.WriteQuoted(s.PrioritizedPrimaryField.DBName)
		// 			_ = builder.WriteByte(' ')
		// 		} else {
		// 			_, _ = builder.WriteString("(SELECT NULL FROM ")
		// 			_, _ = builder.WriteString(d.DummyTableName())
		// 			_, _ = builder.WriteString(")")
		// 		}
		// 	}
		// }

		if offset := limit.Offset; offset > 0 {
			_, _ = builder.WriteString(" OFFSET ")
			_, _ = builder.WriteString(strconv.Itoa(offset))
			_, _ = builder.WriteString(" ROWS")
		}
		if limit := limit.Limit; limit != nil && *limit >= 0 {
			_, _ = builder.WriteString(" FETCH NEXT ")
			_, _ = builder.WriteString(strconv.Itoa(*limit))
			_, _ = builder.WriteString(" ROWS ONLY")
		}
	}
}
```
注释到这几句就正常了， 没看明白这几行是用于什么场景的

**Comment by iTanken** [comment]
> 注释到这几句就正常了， 没看明白这几行是用于什么场景的

用来在分页查询时如果没有指定排序方式的话使用主键作为默认排序方式。

在 Oracle 数据库中，如果你使用 `OFFSET` 进行分页查询，通常建议在查询中显式指定排序方式，尤其是在使用 `OFFSET` 和 `FETCH NEXT` 进行分页时。

原因是，`OFFSET` 和 `FETCH NEXT` 语法是和排序相关的，如果没有明确指定排序方式，查询结果的顺序可能是不确定的。在分页查询中，不确定的顺序可能导致在不同页之间的重复或遗漏的数据。

示例：

```sql
SELECT *
FROM your_table
ORDER BY your_column
OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
```

在上面的示例中，`ORDER BY your_column` 明确指定了排序方式，确保在进行分页查询时结果是可预测的。如果你省略了 `ORDER BY` 子句，查询结果的顺序可能会随数据库的实现而变化，可能不符合你的预期。

因此，为了确保分页查询的结果是有序的，建议在使用 `OFFSET` 和 `FETCH NEXT` 进行分页时，总是显式指定排序方式。

**Comment by SheltonZhu** [comment]
> > 注释到这几句就正常了， 没看明白这几行是用于什么场景的
> 
> 用来在分页查询时如果没有指定排序方式的话使用主键作为默认排序方式。
> 
> 在 Oracle 数据库中，如果你使用 `OFFSET` 进行分页查询，通常建议在查询中显式指定排序方式，尤其是在使用 `OFFSET` 和 `FETCH NEXT` 进行分页时。
> 
> 原因是，`OFFSET` 和 `FETCH NEXT` 语法是和排序相关的，如果没有明确指定排序方式，查询结果的顺序可能是不确定的。在分页查询中，不确定的顺序可能导致在不同页之间的重复或遗漏的数据。
> 
> 示例：
> 
> ```sql
> SELECT *
> FROM your_table
> ORDER BY your_column
> OFFSET 10 ROWS FETCH NEXT 10 ROWS ONLY;
> ```
> 
> 在上面的示例中，`ORDER BY your_column` 明确指定了排序方式，确保在进行分页查询时结果是可预测的。如果你省略了 `ORDER BY` 子句，查询结果的顺序可能会随数据库的实现而变化，可能不符合你的预期。
> 
> 因此，为了确保分页查询的结果是有序的，建议在使用 `OFFSET` 和 `FETCH NEXT` 进行分页时，总是显式指定排序方式。

明白了这个的作用了，但是为什么count函数会进到这里面来
