### ISSUE TITLE
分页问题

### ISSUE THREAD

**Issue by zhuqiyun** [godoes/gorm-oracle#17]
table.Offset((pageIndex - 1) * pageSize).Limit(pageSize).Find(&items).Offset(-1).Limit(-1).Count(&countTmp)，这种写法在mysql，sqlserver都可以 ，oracle只返回前10条，不管pageIndex是多少，请问有其他写法嘛针对oracle

**Comment by iTanken** [comment]
请问 Oracle 数据库版本是多少？`Oracle 12c` 以下版本是有问题
