### ISSUE TITLE
Oracle stored procedure OUT Variables

### ISSUE THREAD

**Issue by kechkibet** [godoes/gorm-oracle#24]
Hi,
I am getting error numeric or value error: character string buffer too small when trying to map output variables of oracle stored procedure to go variables, kindly assist.

```
result := database.DB.Exec(`BEGIN
    ProcedureName(
        @amount,
        '010',
        @sourceUser,
        @UPN, @IssueDate, @Errno, @Errtxt);
    END;`,
		sql.Named("amount", amount),
		sql.Named("sourceUser", sourceUser),
		sql.Named("UPN", sql.Out{Dest: &outputs.UPN}),
		sql.Named("IssueDate", sql.Out{Dest: &outputs.UPN}),
		sql.Named("Errno", sql.Out{Dest: &outputs.UPN}),
		sql.Named("Errtxt", sql.Out{Dest: &outputs.UPN}))
```

**Comment by iTanken** [comment]
Can you provide a complete example code? I can't see where the problem is based on the information provided.

#### Reference

- https://github.com/sijms/go-ora/blob/master/examples/named_pars/main.go
- https://github.com/sijms/go-ora/blob/master/examples/stored_proc/main.go

> This GORM driver is based on [`go-ora`](https://github.com/sijms/go-ora).

**Comment by iTanken** [comment]
Example of executing a stored procedure:
https://github.com/godoes/gorm-oracle/blob/main/oracle_ora_test.go#L111

> This issue was closed because it has been not responded for a long time.
