### ISSUE TITLE
when a entity has a `[]byte` field, call `AutoMigrate()` throw ` ORA-22859: invalid modification of columns`

### ISSUE THREAD

**Issue by H5Q4** [godoes/gorm-oracle#26]

**Comment by iTanken** [comment]
@H5Q4 I attempted to fix this issue in commit 29d2cfed. Please use the following command to get the latest version for testing:

```shell
go get github.com/godoes/gorm-oracle@29d2cfed
```

If the error persists, please reopen this issue.
