### ISSUE TITLE
密码带特殊字符，报错

### ISSUE THREAD

**Issue by liujun0128** [godoes/gorm-oracle#37]
failed to initialize database, got error parse "oracle://ECAED1:NcW\\!\\": invalid port ":NcW\\!\\" after host
如果添加url编码之后，就报密码错误

**Comment by iTanken** [comment]
请使用 `oracle.BuildUrl` 函数构建连接地址：

```go
func BuildUrl(server string, port int, service, user, password string, options map[string]string) string
```

无端口号或使用默认端口号 `port` 传 `0`。
