### ISSUE TITLE
精度丢失问题

### ISSUE THREAD

**Issue by inn87** [godoes/gorm-oracle#39]
用interface{}任意类型接受 源码会将oracle的number类型转为golang中float64类型 如果number长度大于17位则会丢失精度！

**Comment by iTanken** [comment]
在 Go 中要确保数字精度不会丢失，应该使用 `string` 或其他自定义类型，而不是使用 `interface{}` 或 `float64`。

> `ChatGPT`: 当你使用 Go 语言与数据库进行交互时，如果从数据库读取的数据是数字类型，并且你使用 `interface{}` 类型来接收这些数字，那么当这些数字超过一定的位数时（例如超过 17 位），可能会丢失精度。这是因为默认情况下，Go 会将这些数字类型转换为 `float64`，而 `float64` 具有有限的精度，大约为 15-17 位有效数字。当处理超过 17 位的数字时，`float64` 可能无法精确表示这些数字，导致精度丢失。
> `float64` 是一种浮点数类型，采用 IEEE 754 双精度浮点数格式。它的有效位数是 53 位二进制数字，相当于 15-17 位十进制数字。因此，当数字长度大于 17 位时，`float64` 可能无法精确表示这个数字，导致精度丢失。
