### ISSUE TITLE
列名大小写问题

### ISSUE THREAD

**Issue by dagehuifei** [godoes/gorm-oracle#8]
查询在结构体中column需要指定为全大写才能查询到数据，全小写则不可以

**Comment by iTanken** [comment]
```go
url := oracle.BuildUrl("127.0.0.1", "1521", "service", "user", "password", options)
dialector := oracle.New(oracle.Config{
  DSN:                 url,
  IgnoreCase:          false, // 查询条件值是否不区分大小写
  NamingCaseSensitive: true,  // 命名是否区分大小写
})
```

在 Oracle 数据库中，字段 `"field_name"` 和 `field_name` 属于不同的字段。未使用双引号包裹的字段名和表名会自动转换为大写，无法匹配使用双引号包裹的小写字段名和表名。

如果启用了 `NamingCaseSensitive` 选项，GORM 驱动会使用双引号包裹生成的字段名和表名，就会区分大小写。若不需要区分大小写请关闭此选项，但必须保证数据库中的字段名和表名都是大写。

如果还有问题，请进一步提供问题详细说明，如使用 GORM 的相关代码及对应执行的 SQL 语句。
